---
rows: 20  # integer greater than 20
columns: 20  # integer greater than 20
starting_configuration: 'pentadecathlon'  # options are 'blinker', 'glider', 'r-pentomino', 'toad', 'pulsar', 'pentadecathlon', 'lightweight_spaceship'