sudo: required
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-python .
script:
  - docker run -it --rm jeremymiller/life-python pep8 life
  - docker run -it --rm jeremymiller/life-python pylint life
  - docker run -it --rm jeremymiller/life-python py.test --capture=sys --cov=life --cov-report=
after_success:
  - docker run -it --rm jeremymiller/life-python COVERALLS_REPO_TOKEN=$COVERALLS_REPO_TOKEN coveralls
