sudo: required
language: python
python:
  - '3.5'
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-python .
script:
  - pep8 life
  - pylint life
  - py.test --cov=life --cov-report= --capture=sys
after_success:
  - coveralls
