sudo: required
language: python
python:
  - '3.5'
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-python .
script:
  - pep8 life
  - pylint life
  - coverage run py.test --capture=sys
after_success:
  - coveralls
