sudo: required
language: python
python:
  - "3.5"
services:
  - docker
before_install:
  - docker build -t jeremymiller/life-python .
script:
  coverage run --source=life setup.py test
after_success:
  coveralls
